[2023-05-11 03:19:34 -0500] [2305] [INFO] Starting gunicorn 20.1.0
[2023-05-11 03:19:34 -0500] [2305] [INFO] Listening at: http://0.0.0.0:10086 (2305)
[2023-05-11 03:19:34 -0500] [2305] [INFO] Using worker: gthread
[2023-05-11 03:19:34 -0500] [2306] [INFO] Booting worker with pid: 2306
[2023-05-11 03:19:34 -0500] [2307] [INFO] Booting worker with pid: 2307
[2023-05-11 03:19:34 -0500] [2308] [INFO] Booting worker with pid: 2308
[2023-05-11 03:19:34 -0500] [2309] [INFO] Booting worker with pid: 2309
[2023-05-11 03:19:34 -0500] [2310] [INFO] Booting worker with pid: 2310
[2023-05-11 03:19:34 -0500] [2311] [INFO] Booting worker with pid: 2311
[2023-05-11 03:19:34 -0500] [2312] [INFO] Booting worker with pid: 2312
[2023-05-11 03:19:34 -0500] [2313] [INFO] Booting worker with pid: 2313
[2023-05-11 03:19:35 -0500] [2314] [INFO] Booting worker with pid: 2314
[2023-05-11 03:19:35 -0500] [2310] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/nox/.local/lib/python3.10/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/mnt/c/Users/sa_le/Music/WGDashboard-main/src/dashboard.py", line 1687, in run_dashboard
    app_ip = config.get("Server", "app_ip")
  File "/usr/lib/python3.10/configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.10/configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Server'
[2023-05-11 03:19:35 -0500] [2310] [INFO] Worker exiting (pid: 2310)
[2023-05-11 03:19:35 -0500] [2315] [INFO] Booting worker with pid: 2315
[2023-05-11 03:19:35 -0500] [2316] [INFO] Booting worker with pid: 2316
[2023-05-11 03:19:35 -0500] [2313] [INFO] Worker exiting (pid: 2313)
[2023-05-11 03:19:35 -0500] [2314] [INFO] Worker exiting (pid: 2314)
[2023-05-11 03:19:35 -0500] [2315] [INFO] Worker exiting (pid: 2315)
[2023-05-11 03:19:35 -0500] [2316] [INFO] Worker exiting (pid: 2316)
[2023-05-11 03:19:36 -0500] [2309] [INFO] Worker exiting (pid: 2309)
[2023-05-11 03:19:36 -0500] [2306] [INFO] Worker exiting (pid: 2306)
[2023-05-11 03:19:36 -0500] [2307] [INFO] Worker exiting (pid: 2307)
[2023-05-11 03:19:36 -0500] [2308] [INFO] Worker exiting (pid: 2308)
[2023-05-11 03:19:36 -0500] [2311] [INFO] Worker exiting (pid: 2311)
[2023-05-11 03:19:36 -0500] [2312] [INFO] Worker exiting (pid: 2312)
[2023-05-11 03:19:36 -0500] [2305] [INFO] Shutting down: Master
[2023-05-11 03:19:36 -0500] [2305] [INFO] Reason: Worker failed to boot.
